services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elastic
    volumes:
      - ./.elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"

volumes:
  elastic: ~