name: Build and Test on Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
      SERVER_ADDRESS: ":8080"
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
    steps:
    - uses: actions/checkout@v3
    - run: |
        # Create with liberal rights, otherwise cache action will complain
        # about permission errors.
        sudo mkdir -p /nix/store
        sudo chmod -R 777 /nix
    - name: Cache nix env take N+1
      id: myCacheStep
      uses: actions/cache@v2
      with:
        path: |
          # See https://github.com/actions/cache/pull/726
          /nix/store/**
          # Missing something?
          /nix/var/nix/*/*
          /nix/var/nix/db/*
          /nix/var/nix/db/*/**
          !/nix/var/nix/daemon-socket/socket
          !/nix/var/nix/userpool/*
          !/nix/var/nix/gc.lock
          !/nix/var/nix/db/big-lock
          !/nix/var/nix/db/reserved
        key: ${{ runner.os }}-nix-store

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install custom nix env
      if: steps.myCacheStep.outputs.cache-hit != 'true'
      run: nix-env -f shell.nix -i '.*'
    - name: Start Containers
      run: nix-shell --run "docker compose up --build -d"
    - name: Install API dependencies
      run: nix-shell --run "go build"
    - name: Run tests
      run: nix-shell --run "go test -v ./tests"